# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rules.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(817, 445)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 241, 71))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 100, 681, 281))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setOverwriteMode(False)
        self.plainTextEdit.setTabStopWidth(94)
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Rules:</span></p></body></html>"))
        self.plainTextEdit.setPlainText(_translate("Dialog", "Batting\n"
"● 1 point for 2 runs scored\n"
"● Additional 5 points for half century\n"
"● Additional 10 points for century\n"
"● 2 points for strike rate (runs/balls faced) of 80-100\n"
"● Additional 4 points for strike rate>100\n"
"● 1 point for hitting a boundary (four) and 2 points for over boundary (six)\n"
"Bowling\n"
"● 10 points for each wicket\n"
"● Additional 5 points for three wickets per innings\n"
"● Additional 10 points for 5 wickets or more in innings\n"
"● 4 points for economy rate (runs given per over) between 3.5 and 4.5\n"
"● 7 points for economy rate between 2 and 3.5\n"
"● 10 points for economy rate less than 2\n"
"Fielding\n"
"● 10 points each for catch/stumping/run out"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
